esphome:
  name: woleix-ac-controller
  friendly_name: Woleix AC Controller
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.253
    subnet: 255.255.255.0
    gateway: 192.168.1.1

web_server:
  port: 80
  include_internal: true

external_components:
  - source: github://ok11/esphome-external-components/esphome
    components: [ climate_ir_woleix ]
    ref: main
    refresh: 1h

remote_transmitter:
  pin: GPIO20
  carrier_duty_percent: 50%
  id: woleix_ac_ir
  non_blocking: true

button:
  - platform: template
    id: power_pronto
    name: "Power Pronto"
    on_press:
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0022 0000 0158 00AF 0014 0018 0014 0018 0014 0042 0014 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0042 0014 0042 0014 0018 0014 0042 0014 0042 0014 0042 0014 0042 0014 0042 0014 0018 0014 0018 0014 0042 0014 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0042 0014 0042 0014 0018 0014 0043 0013 0042 0014 0042 0014 0042 0014 0042 0014 0483"
      - delay: 40ms
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0004 0000 0159 0056 0014 0483"

  - platform: template
    id: speed_pronto
    name: "Speed Pronto"
    on_press:
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0022 0000 0158 00B0 0013 0018 0014 0018 0014 0041 0014 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0042 0014 0042 0014 0018 0014 0040 0016 0043 0013 0043 0013 003D 0019 0040 0015 0018 0014 003E 0018 0043 0013 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0043 0013 0018 0014 0018 0014 0043 0013 0043 0013 0041 0014 0043 0013 0043 0013 0483"
      - delay: 40ms
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0004 0000 0159 0056 0014 0483"

  - platform: template
    id: temp_up_pronto
    name: "Temp+ Pronto"
    on_press:
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0022 0000 0158 00B0 0013 0018 0014 0017 0014 0043 0013 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0042 0014 0042 0014 0018 0014 0042 0014 0042 0014 0042 0014 0042 0014 0042 0014 0042 0014 0018 0014 0042 0014 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0042 0014 0018 0014 0042 0014 0042 0014 0042 0014 0042 0014 0042 0014 0483"
      - delay: 40ms
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0004 0000 0159 0056 0014 0483"

  - platform: template
    id: mode_pronto
    name: "Mode Pronto"
    on_press:
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0022 0000 0159 00AF 0014 0018 0014 0018 0014 0043 0013 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0043 0013 0043 0013 0018 0014 0043 0013 0043 0013 0043 0013 0043 0013 0043 0013 0043 0013 0018 0014 0043 0013 0043 0013 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0043 0013 0018 0014 0018 0014 0043 0013 0043 0013 0043 0013 0042 0014 0483"
      - delay: 40ms
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0004 0000 0159 0056 0014 0483"

  - platform: template
    id: temp_down_pronto
    name: "Temp- Pronto"
    on_press:
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0022 0000 0158 00AF 0014 0018 0014 0018 0014 0043 0013 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0042 0014 0042 0014 0018 0014 0042 0014 0042 0014 0042 0014 0042 0014 0042 0014 0042 0014 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0042 0014 0042 0014 0042 0014 0042 0014 0042 0014 0042 0014 0042 0014 0483"
      - delay: 40ms
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0004 0000 0159 0056 0014 0483"

  - platform: template
    id: timer_pronto
    name: "Timer Pronto"
    on_press:
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0022 0000 0159 00AF 0014 0018 0014 0018 0014 0043 0013 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0043 0013 0043 0013 0018 0014 0043 0013 0043 0013 0043 0013 0043 0013 0042 0014 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0018 0014 0042 0014 0042 0014 0042 0014 0042 0014 0042 0014 0042 0014 0042 0014 0042 0014 0483"
      - delay: 40ms
      - remote_transmitter.transmit_pronto:
          data: "0000 006D 0004 0000 0159 0056 0014 0483"

  - platform: template
    id: power
    name: "Power NEC"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xFB04
          command_repeats: 1
  
  - platform: template
    id: speed
    name: "Speed NEC"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xF906
          command_repeats: 1

  - platform: template
    id: temp_up
    name: "Temp+ NEC"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xFA05
          command_repeats: 1

  - platform: template
    id: mode
    name: "Mode NEC"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xF20D
          command_repeats: 1

  - platform: template
    id: temp_down
    name: "Temp- NEC"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xFE01
          command_repeats: 1

  - platform: template
    id: timer
    name: "Timer NEC"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xFF00
          command_repeats: 1


climate:
  - platform: climate_ir_woleix
    name: "Woleix AC"
    id: woleix_ac
    transmitter_id: woleix_ac_ir
    sensor: woleix_ac_current_temperature
    humidity_sensor: woleix_ac_current_humidity

sensor:
  - platform: dht
    model: DHT11
    pin: GPIO4
    id: woleix_ac_dht
    temperature:
      name: Temperature
      id: woleix_ac_current_temperature
    humidity:
      name: Humidity
      id: woleix_ac_current_humidity
    update_interval: 60s

binary_sensor:
  - platform: homeassistant
    id: socket_state
    entity_id: switch.woleix_power

  - platform: gpio
    id: reset_button
    name: Reset AC
    internal: true
    pin: 
      number: GPIO01
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on: 3s
      - delayed_off: 10ms
    on_press:
      - if:
          condition:
            lambda: return id(woleix_ac).is_on();
          then:
            - lambda: id(power).press();
            - delay: 30s
      - if:
          condition:
            lambda: return id(socket_state).has_state() && id(socket_state).state;
          then:
            - homeassistant.service:
                service: switch.turn_off
                data:
                  entity_id: switch.woleix_power
            - delay: 30s
            - homeassistant.service:
                service: switch.turn_on
                data:
                  entity_id: switch.woleix_power
      - lambda: id(woleix_ac).reset_state();
